image: microsoft/dotnet:2.1.300-preview2-sdk-alpine

stages:
  - init
  - restore
  - build
  - test

dotnet_init:
  stage: init
  script:
    - dotnet --version
dotnet_restore:
  stage: restore
  script:
    - dotnet restore

dotnet_build:
  stage: build
  script:
    - dotnet build
dotnet_test:
  stage: test
  script:
    - dotnet test --no-build Build.Tests