image: microsoft/dotnet:2.1.300-preview2-sdk-alpine

stages:
  - restore
  - build
  - test

restore:
  stage: restore
  script:
    - dotnet restore

build:
  stage: build
  script:
    - dotnet build
test:
  stage: test
  script:
    - dotnet test --no-build Build.Tests