image: microsoft/dotnet-nightly:2.1-runtime-deps-alpine3.7

stages:
  - dotnet

build:
  stage: dotnet
  script:
    - find .
    - dotnet restore
    - dotnet build
    - dotnet test --no-build Build.Tests