image: microsoft/dotnet:2.1.300-preview2-sdk-alpine

stages:
  - dotnet

restore:
  stage: dotnet
  script:
    - find .
    - dotnet restore
    - dotnet build
    - dotnet test --no-build Build.Tests