stages:
  - init
  - restore
  - build
  - test

job:
  stage: init
  script:
    - dotnet --version
job:
  stage: restore
  script:
    - dotnet restore
job:
  stage: build
  script:
    - dotnet build
job:
  stage: test
  script:
    - dotnet test --no-build Build.Tests