#deploy:
#  provider: pages
#  skip-cleanup: true
#  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
#  keep-history: true
#  on:
#    branch: master
notifications:
  slack: build-core:9zFwG1mZVRxt2cNeW1HO3vv2
language: csharp
dist: trusty
mono: none
dotnet: 2.1-sdk
script:
  - find .
  - dotnet restore
  - dotnet build
  - dotnet test --no-build Build.Tests