#---------------------------------#
#      general configuration      #
#---------------------------------#

version: 1.0.0.{build}-{branch} 

skip_tags: true

#---------------------------------#
#    environment configuration    #
#---------------------------------#

image: Visual Studio 2017 Preview

clone_depth: 1

nuget:  
  disable_publish_on_pr: true

environment:
  SONARCLOUDTOKEN:
    secure: M3l9SYJrD73aoBF99EQCzsiJDPdlaePK6lxYcnVLEhF2TL9OupY0ApriMfJK12s9
  COVERALLSREPOTOKEN:
    secure: cwLai3P4zgzInidPmgHoWnjTRlWW6hOA75eUoorKMfTi8oR4/oJjDDgXqO2uM6lj

build_script:
  - bash install.sh
  - dotnet packages/sonar-scanner-msbuild-4.2.0.1214-netcoreapp2.0/SonarScanner.MSBuild.dll begin /d:sonar.login="$SONARCLOUDTOKEN" /k:"build-core" /d:sonar.host.url="https://sonarcloud.io" /n:"build" /v:"1.0" /d:sonar.cs.opencover.reportsPaths="Build.Tests/coverage.xml" /d:sonar.coverage.exclusions="**/*Test*.cs" /d:sonar.organization="hack2root-github" /d:sonar.verbose=true 
  - dotnet test --no-build Build.Tests /p:CollectCoverage=true /p:CoverletOutputFormat=opencover --configuration Release 
  - dotnet packages/sonar-scanner-msbuild-4.2.0.1214-netcoreapp2.0/SonarScanner.MSBuild.dll end /d:sonar.login="$SONARCLOUDTOKEN" 
  - bash coveralls.io
