#---------------------------------#
#      general configuration      #
#---------------------------------#

version: 1.0.0.{build}-{branch} 

skip_tags: true

#---------------------------------#
#    environment configuration    #
#---------------------------------#

image: Visual Studio 2017 Preview

clone_depth: 1

nuget:  
  disable_publish_on_pr: true

environment:
  SONARCLOUDTOKEN:
    secure: J/Io2E9jT7TQh9FRDeUHNxn+je/4Jzdnxr1Nz/EYaXEr3n31u9eNA/HrLL87o1a8
  COVERALLSREPOTOKEN:
    secure: cwLai3P4zgzInidPmgHoWnjTRlWW6hOA75eUoorKMfTi8oR4/oJjDDgXqO2uM6lj

build_script:
  - bash install.sh
  - dotnet packages/sonar-scanner-msbuild-4.2.0.1214-netcoreapp2.0/SonarScanner.MSBuild.dll begin /d:sonar.login="$COVERALLSREPOTOKEN" /k:"build-core" /d:sonar.host.url="https://sonarcloud.io" /n:"build" /v:"1.0" /d:sonar.cs.opencover.reportsPaths="coverage/opencover.xml" /d:sonar.coverage.exclusions="**/*Test*.cs" /d:sonar.organization="hack2root-github"
  - dotnet build --configuration Release
  - packages/OpenCover.4.6.519/tools/OpenCover.Console.exe -oldstyle -output:"coverage/opencover.xml" -register:user -target:"c:\Program Files\dotnet\dotnet.exe" -targetargs:"test -f netcoreapp2.0 --configuration Release Build.Tests/Build.Tests.csproj" -mergeoutput -hideskipped:File -searchdirs:Build.Tests/bin/Release/netcoreapp2.1 -filter:"+[Build*]* -[Build.*Tests*]*"
  - dotnet packages/sonar-scanner-msbuild-4.2.0.1214-netcoreapp2.0/SonarScanner.MSBuild.dll end /d:sonar.login="$COVERALLSREPOTOKEN"
