#---------------------------------#
#      general configuration      #
#---------------------------------#

version: 1.0.0.{build}-{branch}

skip_tags: true

#---------------------------------#
#    environment configuration    #
#---------------------------------#

image: Visual Studio 2017 Preview

clone_depth: 1

nuget:
    disable_publish_on_pr: true

environment:
    CODECOVTOKEN:
        secure: ctTXke94UzfiYDCYUOCpW9NfXxMz5fCUXIYMffk6U5+Ts9rfpOxYU/wfoLHnN20O
    SONARCLOUDTOKEN:
        secure: M3l9SYJrD73aoBF99EQCzsiJDPdlaePK6lxYcnVLEhF2TL9OupY0ApriMfJK12s9
    COVERALLS_REPO_TOKEN:
        secure: cwLai3P4zgzInidPmgHoWnjTRlWW6hOA75eUoorKMfTi8oR4/oJjDDgXqO2uM6lj

cache:
    - packages -> **\packages.config

install:
    - bash install.sh
    - dotnet restore

before_build:
    - choco install opencover.portable
    - choco install codecov
    - choco install xunit

build_script:
    - ps: ./coverage.ps1
    - bash coveralls.sh

build:
    project: Build.sln
    verbosity: minimal

test_script:
#    - bash install.sh
    - dotnet restore
    - bash codecov.sh
    - bash coveralls.sh
#    - ps: ./coverage.ps1
